FROM fabric8/java-centos-openjdk8-jdk
# FROM openjdk:8
# FROM frolvlad/alpine-oraclejdk8

ENV pinotVersion="SNAPSHOT-2017-06-09T035652Z" archiveName="pinot-0.016-pkg.zip"

LABEL version="1.1"

#RUN apk --update add unzip wget bash ca-certificates
RUN yes | yum install unzip wget

RUN mkdir -p /opt/pinot-0.016 && cd /opt/pinot-0.016 && wget https://github.com/linkedin/pinot/releases/download/${pinotVersion}/${archiveName} && unzip ${archiveName} && rm ${archiveName}

WORKDIR /opt/pinot-0.016
