FROM jfim/pinot

EXPOSE 9000/tcp

WORKDIR /opt/pinot-0.016

RUN mkdir -p /data/pinot-server/data; \
    mkdir -p /data/pinot-server/segments

ENTRYPOINT ["bash", "-c", "/opt/pinot-0.016/bin/start-server.sh -zkAddress $ZK_ADDRESS -dataDir /data/pinot-server/data -segmentDir /data/pinot-server/segments"]
