FROM jfim/pinot

EXPOSE 9000/tcp

WORKDIR /opt/pinot-0.016

RUN mkdir -p /data/pinot-controller-datadir

ENTRYPOINT ["bash", "-c", "/opt/pinot-0.016/bin/start-controller.sh -zkAddress $ZK_ADDRESS -dataDir /data/pinot-controller-datadir"]
