FROM fabric8/java-centos-openjdk8-jdk
# FROM openjdk:8
# FROM frolvlad/alpine-oraclejdk8

LABEL version="1.1"

#RUN apk --update add unzip wget bash ca-certificates
RUN yes | yum install unzip wget

ARG pinotVersion
ARG archiveName
ENV pinotVersion=${pinotVersion:-SNAPSHOT-2017-06-20T222518Z} archiveName=${archiveName:-pinot-0.016-pkg.zip}

RUN mkdir -p /opt/pinot-0.016 && cd /opt/pinot-0.016 && wget https://github.com/linkedin/pinot/releases/download/${pinotVersion}/${archiveName} && unzip ${archiveName} && rm ${archiveName}

WORKDIR /opt/pinot-0.016
