FROM jfim/pinot

EXPOSE 9000/tcp

WORKDIR /opt/pinot-0.016

ENTRYPOINT ["bash", "-c", "/opt/pinot-0.016/bin/start-controller.sh -zkAddress $ZK_ADDRESS"]

VOLUME ["/pinot-server", "/pinot-broker", "/pinot-controller"]
