ARG pinotVersion
FROM jfim/pinot:$pinotVersion

EXPOSE 9000/tcp

WORKDIR /opt/pinot-0.016

RUN mkdir -p /data/pinot-controller-datadir

ENTRYPOINT /opt/pinot-0.016/bin/start-controller.sh -zkAddress $ZK_ADDRESS -dataDir /data/pinot-controller-datadir -controllerHost $(hostname --fqdn)
