---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pinot-datadir-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pinot-controller-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pinot-controller
    spec:
      containers:
      - name: pinot-controller
        image: jfim/pinot-controller:latest
        ports:
        - containerPort: 9000
        env:
        - name : ZK_ADDRESS
          value: "zk-headless:2181"
        volumeMounts:
        - name: pinot-datadir
          mountPath: /var/lib/pinot
      volumes:
        - name: pinot-datadir
          persistentVolumeClaim:
            claimName: pinot-datadir-pvc
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pinot-broker-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pinot-broker
    spec:
      containers:
      - name: pinot-broker
        image: jfim/pinot-broker:latest
        ports:
        - containerPort: 9000
        env:
        - name : ZK_ADDRESS
          value: "zk-headless:2181"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pinot-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pinot-server
    spec:
      containers:
      - name: pinot-server
        image: jfim/pinot-server:latest
        ports:
        - containerPort: 9000
        env:
        - name : ZK_ADDRESS
          value: "zk-headless:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: pinot-controller-headless
  labels:
    app: pinot-controller
spec:
  type: NodePort
  ports:
  - port: 9000
    name: pinot-controller-api
  selector:
    app: pinot-controller
